name: Setup
description: "Setup mise dependencies"
inputs:
  workdir:
    description: "Working directory"
    required: true
runs:
  using: "composite"
  steps:
    - uses: jdx/mise-action@v3
      with:
        working_directory: ${{ inputs.workdir }}
